# Generated by Django 6.0.7 on 2026-10-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_is_verified_purchase_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmet',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
